/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ClaimStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'awaitingInfo' : null } |
  { 'rejected' : null };
export type ExternalBlob = Uint8Array;
export interface PaginationParams { 'page' : bigint, 'pageSize' : bigint }
export type PayoutMethod = {
    'atmCard' : { 'cardType' : string, 'bank' : string, 'cardNumber' : string }
  } |
  { 'certifiedCheck' : { 'bank' : string, 'payeeName' : string } } |
  {
    'bankTransfer' : {
      'bank' : string,
      'routingNumber' : string,
      'accountName' : string,
      'accountNumber' : string,
    }
  };
export interface Testimonial {
  'title' : string,
  'name' : string,
  'quote' : string,
  'income' : string,
  'image' : ExternalBlob,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WinnerClaim {
  'id' : string,
  'status' : ClaimStatus,
  'payoutMethod' : PayoutMethod,
  'claimant' : Principal,
  'winnerId' : string,
  'submissionTimestamp' : Time,
  'idCardImageId' : [] | [string],
  'selfieImageId' : [] | [string],
  'adminResponse' : [] | [string],
}
export interface WinningEntry {
  'id' : string,
  'prizeNumber' : string,
  'name' : string,
  'isClaimed' : boolean,
  'ticketNumber' : string,
  'claimedBy' : [] | [Principal],
  'claimTimestamp' : [] | [Time],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTestimonial' : ActorMethod<[Testimonial], undefined>,
  'adminResponse' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimWinningEntry' : ActorMethod<[string], undefined>,
  'getAllClaims' : ActorMethod<
    [[] | [ClaimStatus], PaginationParams],
    Array<WinnerClaim>
  >,
  'getAllWinningEntries' : ActorMethod<[], Array<WinningEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEntryByNumber' : ActorMethod<[string], [] | [WinningEntry]>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeTestimonial' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitWinnerClaim' : ActorMethod<[WinnerClaim], undefined>,
  'updateClaimStatus' : ActorMethod<[string, ClaimStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];