/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Testimonial = IDL.Record({
  'title' : IDL.Text,
  'name' : IDL.Text,
  'quote' : IDL.Text,
  'income' : IDL.Text,
  'image' : ExternalBlob,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClaimStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'awaitingInfo' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PaginationParams = IDL.Record({
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
});
export const PayoutMethod = IDL.Variant({
  'atmCard' : IDL.Record({
    'cardType' : IDL.Text,
    'bank' : IDL.Text,
    'cardNumber' : IDL.Text,
  }),
  'certifiedCheck' : IDL.Record({ 'bank' : IDL.Text, 'payeeName' : IDL.Text }),
  'bankTransfer' : IDL.Record({
    'bank' : IDL.Text,
    'routingNumber' : IDL.Text,
    'accountName' : IDL.Text,
    'accountNumber' : IDL.Text,
  }),
});
export const Time = IDL.Int;
export const WinnerClaim = IDL.Record({
  'id' : IDL.Text,
  'status' : ClaimStatus,
  'payoutMethod' : PayoutMethod,
  'claimant' : IDL.Principal,
  'winnerId' : IDL.Text,
  'submissionTimestamp' : Time,
  'idCardImageId' : IDL.Opt(IDL.Text),
  'selfieImageId' : IDL.Opt(IDL.Text),
  'adminResponse' : IDL.Opt(IDL.Text),
});
export const WinningEntry = IDL.Record({
  'id' : IDL.Text,
  'prizeNumber' : IDL.Text,
  'name' : IDL.Text,
  'isClaimed' : IDL.Bool,
  'ticketNumber' : IDL.Text,
  'claimedBy' : IDL.Opt(IDL.Principal),
  'claimTimestamp' : IDL.Opt(Time),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTestimonial' : IDL.Func([Testimonial], [], []),
  'adminResponse' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimWinningEntry' : IDL.Func([IDL.Text], [], []),
  'getAllClaims' : IDL.Func(
      [IDL.Opt(ClaimStatus), PaginationParams],
      [IDL.Vec(WinnerClaim)],
      ['query'],
    ),
  'getAllWinningEntries' : IDL.Func([], [IDL.Vec(WinningEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntryByNumber' : IDL.Func([IDL.Text], [IDL.Opt(WinningEntry)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeTestimonial' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitWinnerClaim' : IDL.Func([WinnerClaim], [], []),
  'updateClaimStatus' : IDL.Func([IDL.Text, ClaimStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Testimonial = IDL.Record({
    'title' : IDL.Text,
    'name' : IDL.Text,
    'quote' : IDL.Text,
    'income' : IDL.Text,
    'image' : ExternalBlob,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClaimStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'awaitingInfo' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PaginationParams = IDL.Record({
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
  });
  const PayoutMethod = IDL.Variant({
    'atmCard' : IDL.Record({
      'cardType' : IDL.Text,
      'bank' : IDL.Text,
      'cardNumber' : IDL.Text,
    }),
    'certifiedCheck' : IDL.Record({
      'bank' : IDL.Text,
      'payeeName' : IDL.Text,
    }),
    'bankTransfer' : IDL.Record({
      'bank' : IDL.Text,
      'routingNumber' : IDL.Text,
      'accountName' : IDL.Text,
      'accountNumber' : IDL.Text,
    }),
  });
  const Time = IDL.Int;
  const WinnerClaim = IDL.Record({
    'id' : IDL.Text,
    'status' : ClaimStatus,
    'payoutMethod' : PayoutMethod,
    'claimant' : IDL.Principal,
    'winnerId' : IDL.Text,
    'submissionTimestamp' : Time,
    'idCardImageId' : IDL.Opt(IDL.Text),
    'selfieImageId' : IDL.Opt(IDL.Text),
    'adminResponse' : IDL.Opt(IDL.Text),
  });
  const WinningEntry = IDL.Record({
    'id' : IDL.Text,
    'prizeNumber' : IDL.Text,
    'name' : IDL.Text,
    'isClaimed' : IDL.Bool,
    'ticketNumber' : IDL.Text,
    'claimedBy' : IDL.Opt(IDL.Principal),
    'claimTimestamp' : IDL.Opt(Time),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTestimonial' : IDL.Func([Testimonial], [], []),
    'adminResponse' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimWinningEntry' : IDL.Func([IDL.Text], [], []),
    'getAllClaims' : IDL.Func(
        [IDL.Opt(ClaimStatus), PaginationParams],
        [IDL.Vec(WinnerClaim)],
        ['query'],
      ),
    'getAllWinningEntries' : IDL.Func([], [IDL.Vec(WinningEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntryByNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(WinningEntry)],
        ['query'],
      ),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeTestimonial' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitWinnerClaim' : IDL.Func([WinnerClaim], [], []),
    'updateClaimStatus' : IDL.Func([IDL.Text, ClaimStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };